runtime:
  cache_dir: ./.cache/antora

site:
  title: Atelier d'ingénierie du chaos OpenShift
  url: https://redhat-scholars.github.io/course-template
  start_page: chaos-engineering::index.adoc

content:
  sources:
    - url: git@github.com:Dave-c-Ross/chaos-engineering-guide.git
      tags: []
      branches: ["5.0"]
      start_path: documentation
    - url: https://github.com/redhat-scholars/chaos-engineering-guide.git
      tags: []
      branches: ["5.0"]
      start_path: documentation

asciidoc:
  attributes:
    release-version: master
    page-pagination: true
    page-toctitle: Contenu
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/mcouliba/course-ui/releases/download/v0.1.9-custom/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./gh-pages
